version: '3'

env:
  K8S_VERSION: "1.29.4"

tasks:
  up:
    cmds:
      - task: apply
      - task: login-argo

  apply:
    cmds:
      - terraform plan -out out.plan
      - terraform apply "out.plan"
      - az aks get-credentials --resource-group gitops --name gitops-aks
  
  destroy:
    cmds:
      - terraform destroy -auto-approve

  force-delete:
    cmds:
      - az group delete -n gitops -y
      - rm *tfstate*

  login-argo:
    # TODO: Add question if port-forward is running
    cmds:
      - read -p "Run in another terminal:kubectl port-forward svc/argo-cd-argocd-server 8080:443 -n argocd"
      - argocd login localhost:8080 --insecure --username admin --password $(kubectl get secrets argocd-initial-admin-secret -ojsonpath='{.data.password}' -n argocd |base64 --decode)
      - open http://localhost:8080

  aks-versions:
    cmds:
      - az aks get-versions --location eastus --output table