version: '3'

env:
  K8S_VERSION: "1.29.4"

tasks:
  up:
    cmds:
      - task: apply
      - task: login-argo

  apply:
    cmds:
      - tofu init -upgrade
      - tofu plan -out out.plan
      - tofu apply "out.plan"
      - az aks get-credentials --resource-group gitops --name gitops-aks
  
  destroy:
    cmds:
      - tofu destroy -auto-approve
  
  argo-rollouts:
    cmds:
      - argocd app sync argocd/istio-base
      - argocd app sync argocd/istiod
      - argocd app sync argocd/istio-ingress
      - argocd app sync argocd/prometheus-operator

  force-delete:
    cmds:
      - az group delete -n gitops -y
      - rm *tfstate*

  login-argo:
    cmds:
      - read -p "Run in another terminal:kubectl port-forward svc/argo-cd-argocd-server 8080:443 -n argocd"
      - argocd login localhost:8080 --insecure --username admin --password $(kubectl get secrets argocd-initial-admin-secret -ojsonpath='{.data.password}' -n argocd |base64 --decode)
      - open http://localhost:8080

  aks-versions:
    cmds:
      - az aks get-versions --location eastus --output table
